# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Tobi vNext"
description: "F#, C#, PowerShell and HTML5 developer; interested in everything tech-related with a strong focus on Microsoft technology."

email: tobias_burger@hotmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Tobias Burger'
author: 'Tobias Burger'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://toburger.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/toburger
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:  facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/toburger
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:  google-plus
#    url: https://google.com/???
#    desc:  Add me on google+
#    share_url:
#    share_title:
#    share_link:

